package com.xuyurepos.vo.manager;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 前台vo对象
 * @author yangfei
 *
 */
public class XuyuContentCardInfoRecordVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.ID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.ACCESS_NUM
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String accessNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.ICCID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String iccid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.IMSI
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String imsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.PROVIDER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER_PLACE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String ownerPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String agency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.CARD_KIND
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String cardKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.BILLING_STATUS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String billingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.COMBO_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String comboType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.COMNO_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String comnoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.TOTAL_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal totalGprs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_GPS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal remainGps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.USE_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal useGprs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MESSAGE_COUNT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Integer messageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.ESTABLISH_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date establishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.ACTIVATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date activateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.DEADLINE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date deadlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String waitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date waitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.WORKING_CONDITION
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String workingCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.PAYMENT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ESTABLISH
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date realEstablish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ACTIVATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date realActivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_DEADLINE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date realDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBOTYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String realCombotype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBONAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String realComboname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.UNIT_COST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal unitCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal monthFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal agencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REVENUE_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal revenueFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.LASTMONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal lastmonthFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal remainFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal realProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal agencyProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.PARENT_AGENTCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String parentAgentcy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_FIRST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String markFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal markProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.IMPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String importBatchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.EXPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String exportBatchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.MGR_OWN_FLAG
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String mgrOwnFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_INFO_RECORD.PRICE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ID
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.ID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ID
     *
     * @param id the value for XUYU_CONTENT_CARD_INFO_RECORD.ID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ACCESS_NUM
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.ACCESS_NUM
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getAccessNum() {
        return accessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ACCESS_NUM
     *
     * @param accessNum the value for XUYU_CONTENT_CARD_INFO_RECORD.ACCESS_NUM
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setAccessNum(String accessNum) {
        this.accessNum = accessNum == null ? null : accessNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ICCID
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.ICCID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ICCID
     *
     * @param iccid the value for XUYU_CONTENT_CARD_INFO_RECORD.ICCID
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.IMSI
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.IMSI
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.IMSI
     *
     * @param imsi the value for XUYU_CONTENT_CARD_INFO_RECORD.IMSI
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PROVIDER
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.PROVIDER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PROVIDER
     *
     * @param provider the value for XUYU_CONTENT_CARD_INFO_RECORD.PROVIDER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER_PLACE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.OWNER_PLACE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getOwnerPlace() {
        return ownerPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER_PLACE
     *
     * @param ownerPlace the value for XUYU_CONTENT_CARD_INFO_RECORD.OWNER_PLACE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setOwnerPlace(String ownerPlace) {
        this.ownerPlace = ownerPlace == null ? null : ownerPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.AGENCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY
     *
     * @param agency the value for XUYU_CONTENT_CARD_INFO_RECORD.AGENCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CARD_KIND
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.CARD_KIND
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getCardKind() {
        return cardKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CARD_KIND
     *
     * @param cardKind the value for XUYU_CONTENT_CARD_INFO_RECORD.CARD_KIND
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setCardKind(String cardKind) {
        this.cardKind = cardKind == null ? null : cardKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.BILLING_STATUS
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.BILLING_STATUS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getBillingStatus() {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.BILLING_STATUS
     *
     * @param billingStatus the value for XUYU_CONTENT_CARD_INFO_RECORD.BILLING_STATUS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.COMBO_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.COMBO_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getComboType() {
        return comboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.COMBO_TYPE
     *
     * @param comboType the value for XUYU_CONTENT_CARD_INFO_RECORD.COMBO_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setComboType(String comboType) {
        this.comboType = comboType == null ? null : comboType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.COMNO_NAME
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.COMNO_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getComnoName() {
        return comnoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.COMNO_NAME
     *
     * @param comnoName the value for XUYU_CONTENT_CARD_INFO_RECORD.COMNO_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setComnoName(String comnoName) {
        this.comnoName = comnoName == null ? null : comnoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.TOTAL_GPRS
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.TOTAL_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getTotalGprs() {
        return totalGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.TOTAL_GPRS
     *
     * @param totalGprs the value for XUYU_CONTENT_CARD_INFO_RECORD.TOTAL_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setTotalGprs(BigDecimal totalGprs) {
        this.totalGprs = totalGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_GPS
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_GPS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getRemainGps() {
        return remainGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_GPS
     *
     * @param remainGps the value for XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_GPS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRemainGps(BigDecimal remainGps) {
        this.remainGps = remainGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.USE_GPRS
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.USE_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getUseGprs() {
        return useGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.USE_GPRS
     *
     * @param useGprs the value for XUYU_CONTENT_CARD_INFO_RECORD.USE_GPRS
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setUseGprs(BigDecimal useGprs) {
        this.useGprs = useGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MESSAGE_COUNT
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MESSAGE_COUNT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Integer getMessageCount() {
        return messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MESSAGE_COUNT
     *
     * @param messageCount the value for XUYU_CONTENT_CARD_INFO_RECORD.MESSAGE_COUNT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ESTABLISH_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.ESTABLISH_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ESTABLISH_DATE
     *
     * @param establishDate the value for XUYU_CONTENT_CARD_INFO_RECORD.ESTABLISH_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ACTIVATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.ACTIVATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getActivateDate() {
        return activateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.ACTIVATE_DATE
     *
     * @param activateDate the value for XUYU_CONTENT_CARD_INFO_RECORD.ACTIVATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setActivateDate(Date activateDate) {
        this.activateDate = activateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.DEADLINE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.DEADLINE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getDeadlineDate() {
        return deadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.DEADLINE_DATE
     *
     * @param deadlineDate the value for XUYU_CONTENT_CARD_INFO_RECORD.DEADLINE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setDeadlineDate(Date deadlineDate) {
        this.deadlineDate = deadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.WAIT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getWaitType() {
        return waitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_TYPE
     *
     * @param waitType the value for XUYU_CONTENT_CARD_INFO_RECORD.WAIT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setWaitType(String waitType) {
        this.waitType = waitType == null ? null : waitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.WAIT_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getWaitDate() {
        return waitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WAIT_DATE
     *
     * @param waitDate the value for XUYU_CONTENT_CARD_INFO_RECORD.WAIT_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setWaitDate(Date waitDate) {
        this.waitDate = waitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WORKING_CONDITION
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.WORKING_CONDITION
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getWorkingCondition() {
        return workingCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.WORKING_CONDITION
     *
     * @param workingCondition the value for XUYU_CONTENT_CARD_INFO_RECORD.WORKING_CONDITION
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setWorkingCondition(String workingCondition) {
        this.workingCondition = workingCondition == null ? null : workingCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.OWNER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.OWNER
     *
     * @param owner the value for XUYU_CONTENT_CARD_INFO_RECORD.OWNER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PAYMENT_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.PAYMENT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PAYMENT_TYPE
     *
     * @param paymentType the value for XUYU_CONTENT_CARD_INFO_RECORD.PAYMENT_TYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ESTABLISH
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_ESTABLISH
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getRealEstablish() {
        return realEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ESTABLISH
     *
     * @param realEstablish the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_ESTABLISH
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealEstablish(Date realEstablish) {
        this.realEstablish = realEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ACTIVATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_ACTIVATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getRealActivate() {
        return realActivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_ACTIVATE
     *
     * @param realActivate the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_ACTIVATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealActivate(Date realActivate) {
        this.realActivate = realActivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_DEADLINE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_DEADLINE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getRealDeadline() {
        return realDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_DEADLINE
     *
     * @param realDeadline the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_DEADLINE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealDeadline(Date realDeadline) {
        this.realDeadline = realDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBOTYPE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBOTYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getRealCombotype() {
        return realCombotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBOTYPE
     *
     * @param realCombotype the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBOTYPE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealCombotype(String realCombotype) {
        this.realCombotype = realCombotype == null ? null : realCombotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBONAME
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBONAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getRealComboname() {
        return realComboname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBONAME
     *
     * @param realComboname the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_COMBONAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealComboname(String realComboname) {
        this.realComboname = realComboname == null ? null : realComboname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UNIT_COST
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.UNIT_COST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UNIT_COST
     *
     * @param unitCost the value for XUYU_CONTENT_CARD_INFO_RECORD.UNIT_COST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MONTH_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getMonthFee() {
        return monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MONTH_FEE
     *
     * @param monthFee the value for XUYU_CONTENT_CARD_INFO_RECORD.MONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMonthFee(BigDecimal monthFee) {
        this.monthFee = monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getAgencyFee() {
        return agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_FEE
     *
     * @param agencyFee the value for XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setAgencyFee(BigDecimal agencyFee) {
        this.agencyFee = agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REVENUE_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REVENUE_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getRevenueFee() {
        return revenueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REVENUE_FEE
     *
     * @param revenueFee the value for XUYU_CONTENT_CARD_INFO_RECORD.REVENUE_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRevenueFee(BigDecimal revenueFee) {
        this.revenueFee = revenueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.LASTMONTH_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.LASTMONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getLastmonthFee() {
        return lastmonthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.LASTMONTH_FEE
     *
     * @param lastmonthFee the value for XUYU_CONTENT_CARD_INFO_RECORD.LASTMONTH_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setLastmonthFee(BigDecimal lastmonthFee) {
        this.lastmonthFee = lastmonthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getRemainFee() {
        return remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_FEE
     *
     * @param remainFee the value for XUYU_CONTENT_CARD_INFO_RECORD.REMAIN_FEE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRemainFee(BigDecimal remainFee) {
        this.remainFee = remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.REAL_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getRealProfit() {
        return realProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.REAL_PROFIT
     *
     * @param realProfit the value for XUYU_CONTENT_CARD_INFO_RECORD.REAL_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setRealProfit(BigDecimal realProfit) {
        this.realProfit = realProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getAgencyProfit() {
        return agencyProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_PROFIT
     *
     * @param agencyProfit the value for XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setAgencyProfit(BigDecimal agencyProfit) {
        this.agencyProfit = agencyProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MARK
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK
     *
     * @param mark the value for XUYU_CONTENT_CARD_INFO_RECORD.MARK
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PARENT_AGENTCY
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.PARENT_AGENTCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getParentAgentcy() {
        return parentAgentcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PARENT_AGENTCY
     *
     * @param parentAgentcy the value for XUYU_CONTENT_CARD_INFO_RECORD.PARENT_AGENTCY
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setParentAgentcy(String parentAgentcy) {
        this.parentAgentcy = parentAgentcy == null ? null : parentAgentcy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_FIRST
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MARK_FIRST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getMarkFirst() {
        return markFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_FIRST
     *
     * @param markFirst the value for XUYU_CONTENT_CARD_INFO_RECORD.MARK_FIRST
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMarkFirst(String markFirst) {
        this.markFirst = markFirst == null ? null : markFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MARK_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getMarkProfit() {
        return markProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MARK_PROFIT
     *
     * @param markProfit the value for XUYU_CONTENT_CARD_INFO_RECORD.MARK_PROFIT
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMarkProfit(BigDecimal markProfit) {
        this.markProfit = markProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.CREATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_DATE
     *
     * @param createDate the value for XUYU_CONTENT_CARD_INFO_RECORD.CREATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_USER
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.CREATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.CREATE_USER
     *
     * @param createUser the value for XUYU_CONTENT_CARD_INFO_RECORD.CREATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_DATE
     *
     * @param updateDate the value for XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_USER
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_USER
     *
     * @param updateUser the value for XUYU_CONTENT_CARD_INFO_RECORD.UPDATE_USER
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.IMPORT_BATCHNO
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.IMPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getImportBatchno() {
        return importBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.IMPORT_BATCHNO
     *
     * @param importBatchno the value for XUYU_CONTENT_CARD_INFO_RECORD.IMPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setImportBatchno(String importBatchno) {
        this.importBatchno = importBatchno == null ? null : importBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.EXPORT_BATCHNO
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.EXPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getExportBatchno() {
        return exportBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.EXPORT_BATCHNO
     *
     * @param exportBatchno the value for XUYU_CONTENT_CARD_INFO_RECORD.EXPORT_BATCHNO
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setExportBatchno(String exportBatchno) {
        this.exportBatchno = exportBatchno == null ? null : exportBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MGR_OWN_FLAG
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.MGR_OWN_FLAG
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getMgrOwnFlag() {
        return mgrOwnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.MGR_OWN_FLAG
     *
     * @param mgrOwnFlag the value for XUYU_CONTENT_CARD_INFO_RECORD.MGR_OWN_FLAG
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setMgrOwnFlag(String mgrOwnFlag) {
        this.mgrOwnFlag = mgrOwnFlag == null ? null : mgrOwnFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_NAME
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public String getAgencyName() {
        return agencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_NAME
     *
     * @param agencyName the value for XUYU_CONTENT_CARD_INFO_RECORD.AGENCY_NAME
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName == null ? null : agencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PRICE
     *
     * @return the value of XUYU_CONTENT_CARD_INFO_RECORD.PRICE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_INFO_RECORD.PRICE
     *
     * @param price the value for XUYU_CONTENT_CARD_INFO_RECORD.PRICE
     *
     * @mbggenerated Sat Apr 06 09:12:17 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
