package com.xuyurepos.entity.manager;

import java.util.Date;

public class XuyuMessageLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.ID
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.ACCESS_NUM
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String accessNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.PROVIDER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.OWNER_PLACE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String ownerPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.MESSAGE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.CREATE_USER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_MESSAGE_LOG.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    private String createUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.ID
     *
     * @return the value of XUYU_MESSAGE_LOG.ID
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.ID
     *
     * @param id the value for XUYU_MESSAGE_LOG.ID
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.ACCESS_NUM
     *
     * @return the value of XUYU_MESSAGE_LOG.ACCESS_NUM
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getAccessNum() {
        return accessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.ACCESS_NUM
     *
     * @param accessNum the value for XUYU_MESSAGE_LOG.ACCESS_NUM
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setAccessNum(String accessNum) {
        this.accessNum = accessNum == null ? null : accessNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.PROVIDER
     *
     * @return the value of XUYU_MESSAGE_LOG.PROVIDER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.PROVIDER
     *
     * @param provider the value for XUYU_MESSAGE_LOG.PROVIDER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.OWNER_PLACE
     *
     * @return the value of XUYU_MESSAGE_LOG.OWNER_PLACE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getOwnerPlace() {
        return ownerPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.OWNER_PLACE
     *
     * @param ownerPlace the value for XUYU_MESSAGE_LOG.OWNER_PLACE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setOwnerPlace(String ownerPlace) {
        this.ownerPlace = ownerPlace == null ? null : ownerPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.CREATE_TIME
     *
     * @return the value of XUYU_MESSAGE_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.CREATE_TIME
     *
     * @param createTime the value for XUYU_MESSAGE_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.MESSAGE
     *
     * @return the value of XUYU_MESSAGE_LOG.MESSAGE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.MESSAGE
     *
     * @param message the value for XUYU_MESSAGE_LOG.MESSAGE
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.CREATE_USER
     *
     * @return the value of XUYU_MESSAGE_LOG.CREATE_USER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.CREATE_USER
     *
     * @param createUser the value for XUYU_MESSAGE_LOG.CREATE_USER
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_MESSAGE_LOG.CREATE_USER_NAME
     *
     * @return the value of XUYU_MESSAGE_LOG.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_MESSAGE_LOG.CREATE_USER_NAME
     *
     * @param createUserName the value for XUYU_MESSAGE_LOG.CREATE_USER_NAME
     *
     * @mbggenerated Tue Apr 23 21:00:15 CST 2019
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }
}