package com.xuyurepos.entity.manager;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@SuppressWarnings("serial")
public class XuyuContentCardMgr  implements Serializable{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.ID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.ACCESS_NUM
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String accessNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.ICCID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String iccid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.IMSI
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String imsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.PROVIDER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String provider;
    
    private String ownerPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.AGENCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String agency;
    
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.CARD_KIND
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String cardKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.BILLING_STATUS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String billingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.COMBO_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String comboType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.COMNO_NAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String comnoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.TOTAL_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal totalGprs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REMAIN_GPS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal remainGps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.USE_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal useGprs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MESSAGE_COUNT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private Integer messageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.ESTABLISH_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date establishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.ACTIVATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date activateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.DEADLINE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date deadlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.WAIT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String waitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.WAIT_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date waitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.WORKING_CONDITION
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String workingCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.OWNER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.PAYMENT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_ESTABLISH
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date realEstablish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_ACTIVATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date realActivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_DEADLINE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date realDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_COMBOTYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String realCombotype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_COMBONAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String realComboname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.UNIT_COST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal unitCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal monthFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.AGENCY_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal agencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REVENUE_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal revenueFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.LASTMONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal lastmonthFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REMAIN_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal remainFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.REAL_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal realProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.AGENCY_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal agencyProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MARK
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.PARENT_AGENTCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String parentAgentcy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MARK_FIRST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String markFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MARK_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private BigDecimal markProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.CREATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.CREATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.UPDATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.IMPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String importBatchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.EXPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String exportBatchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_CONTENT_CARD_MGR.MANAGER_FLAG
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    private String managerFlag;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column SYSTEM_ANNEXE.TEST_TYPE
    *
    * @mbggenerated Sun Apr 14 21:50:45 CST 2019
    */
   private String testType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column SYSTEM_ANNEXE.CARD_TYPE
    *
    * @mbggenerated Sun Apr 14 21:50:45 CST 2019
    */
   private String cardType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column SYSTEM_ANNEXE.STANDARD
    *
    * @mbggenerated Sun Apr 14 21:50:45 CST 2019
    */
   private String standard;
   
   private BigDecimal realTotalGprs;

   private BigDecimal realRemainGps;
   
   private String realTestType;
   private String realWaitType;
   private Date realWaitDate;
   
   private String orgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.ID
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.ID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.ID
     *
     * @param id the value for XUYU_CONTENT_CARD_MGR.ID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.ACCESS_NUM
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.ACCESS_NUM
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getAccessNum() {
        return accessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.ACCESS_NUM
     *
     * @param accessNum the value for XUYU_CONTENT_CARD_MGR.ACCESS_NUM
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setAccessNum(String accessNum) {
        this.accessNum = accessNum == null ? null : accessNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.ICCID
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.ICCID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.ICCID
     *
     * @param iccid the value for XUYU_CONTENT_CARD_MGR.ICCID
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.IMSI
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.IMSI
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.IMSI
     *
     * @param imsi the value for XUYU_CONTENT_CARD_MGR.IMSI
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.PROVIDER
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.PROVIDER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.PROVIDER
     *
     * @param provider the value for XUYU_CONTENT_CARD_MGR.PROVIDER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    public String getOwnerPlace() {
		return ownerPlace;
	}

	public void setOwnerPlace(String ownerPlace) {
		this.ownerPlace = ownerPlace;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.AGENCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY
     *
     * @param agency the value for XUYU_CONTENT_CARD_MGR.AGENCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.CARD_KIND
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.CARD_KIND
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getCardKind() {
        return cardKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.CARD_KIND
     *
     * @param cardKind the value for XUYU_CONTENT_CARD_MGR.CARD_KIND
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setCardKind(String cardKind) {
        this.cardKind = cardKind == null ? null : cardKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.BILLING_STATUS
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.BILLING_STATUS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getBillingStatus() {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.BILLING_STATUS
     *
     * @param billingStatus the value for XUYU_CONTENT_CARD_MGR.BILLING_STATUS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.COMBO_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.COMBO_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getComboType() {
        return comboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.COMBO_TYPE
     *
     * @param comboType the value for XUYU_CONTENT_CARD_MGR.COMBO_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setComboType(String comboType) {
        this.comboType = comboType == null ? null : comboType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.COMNO_NAME
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.COMNO_NAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getComnoName() {
        return comnoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.COMNO_NAME
     *
     * @param comnoName the value for XUYU_CONTENT_CARD_MGR.COMNO_NAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setComnoName(String comnoName) {
        this.comnoName = comnoName == null ? null : comnoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.TOTAL_GPRS
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.TOTAL_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getTotalGprs() {
        return totalGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.TOTAL_GPRS
     *
     * @param totalGprs the value for XUYU_CONTENT_CARD_MGR.TOTAL_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setTotalGprs(BigDecimal totalGprs) {
        this.totalGprs = totalGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REMAIN_GPS
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REMAIN_GPS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getRemainGps() {
        return remainGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REMAIN_GPS
     *
     * @param remainGps the value for XUYU_CONTENT_CARD_MGR.REMAIN_GPS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRemainGps(BigDecimal remainGps) {
        this.remainGps = remainGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.USE_GPRS
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.USE_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getUseGprs() {
        return useGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.USE_GPRS
     *
     * @param useGprs the value for XUYU_CONTENT_CARD_MGR.USE_GPRS
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setUseGprs(BigDecimal useGprs) {
        this.useGprs = useGprs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MESSAGE_COUNT
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MESSAGE_COUNT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Integer getMessageCount() {
        return messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MESSAGE_COUNT
     *
     * @param messageCount the value for XUYU_CONTENT_CARD_MGR.MESSAGE_COUNT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.ESTABLISH_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.ESTABLISH_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.ESTABLISH_DATE
     *
     * @param establishDate the value for XUYU_CONTENT_CARD_MGR.ESTABLISH_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.ACTIVATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.ACTIVATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getActivateDate() {
        return activateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.ACTIVATE_DATE
     *
     * @param activateDate the value for XUYU_CONTENT_CARD_MGR.ACTIVATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setActivateDate(Date activateDate) {
        this.activateDate = activateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.DEADLINE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.DEADLINE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getDeadlineDate() {
        return deadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.DEADLINE_DATE
     *
     * @param deadlineDate the value for XUYU_CONTENT_CARD_MGR.DEADLINE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setDeadlineDate(Date deadlineDate) {
        this.deadlineDate = deadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.WAIT_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.WAIT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getWaitType() {
        return waitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.WAIT_TYPE
     *
     * @param waitType the value for XUYU_CONTENT_CARD_MGR.WAIT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setWaitType(String waitType) {
        this.waitType = waitType == null ? null : waitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.WAIT_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.WAIT_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getWaitDate() {
        return waitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.WAIT_DATE
     *
     * @param waitDate the value for XUYU_CONTENT_CARD_MGR.WAIT_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setWaitDate(Date waitDate) {
        this.waitDate = waitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.WORKING_CONDITION
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.WORKING_CONDITION
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getWorkingCondition() {
        return workingCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.WORKING_CONDITION
     *
     * @param workingCondition the value for XUYU_CONTENT_CARD_MGR.WORKING_CONDITION
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setWorkingCondition(String workingCondition) {
        this.workingCondition = workingCondition == null ? null : workingCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.OWNER
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.OWNER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.OWNER
     *
     * @param owner the value for XUYU_CONTENT_CARD_MGR.OWNER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.PAYMENT_TYPE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.PAYMENT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.PAYMENT_TYPE
     *
     * @param paymentType the value for XUYU_CONTENT_CARD_MGR.PAYMENT_TYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_ESTABLISH
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_ESTABLISH
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getRealEstablish() {
        return realEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_ESTABLISH
     *
     * @param realEstablish the value for XUYU_CONTENT_CARD_MGR.REAL_ESTABLISH
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealEstablish(Date realEstablish) {
        this.realEstablish = realEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_ACTIVATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_ACTIVATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getRealActivate() {
        return realActivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_ACTIVATE
     *
     * @param realActivate the value for XUYU_CONTENT_CARD_MGR.REAL_ACTIVATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealActivate(Date realActivate) {
        this.realActivate = realActivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_DEADLINE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_DEADLINE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getRealDeadline() {
        return realDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_DEADLINE
     *
     * @param realDeadline the value for XUYU_CONTENT_CARD_MGR.REAL_DEADLINE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealDeadline(Date realDeadline) {
        this.realDeadline = realDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_COMBOTYPE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_COMBOTYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getRealCombotype() {
        return realCombotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_COMBOTYPE
     *
     * @param realCombotype the value for XUYU_CONTENT_CARD_MGR.REAL_COMBOTYPE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealCombotype(String realCombotype) {
        this.realCombotype = realCombotype == null ? null : realCombotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_COMBONAME
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_COMBONAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getRealComboname() {
        return realComboname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_COMBONAME
     *
     * @param realComboname the value for XUYU_CONTENT_CARD_MGR.REAL_COMBONAME
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealComboname(String realComboname) {
        this.realComboname = realComboname == null ? null : realComboname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.UNIT_COST
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.UNIT_COST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.UNIT_COST
     *
     * @param unitCost the value for XUYU_CONTENT_CARD_MGR.UNIT_COST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MONTH_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getMonthFee() {
        return monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MONTH_FEE
     *
     * @param monthFee the value for XUYU_CONTENT_CARD_MGR.MONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setMonthFee(BigDecimal monthFee) {
        this.monthFee = monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.AGENCY_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getAgencyFee() {
        return agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY_FEE
     *
     * @param agencyFee the value for XUYU_CONTENT_CARD_MGR.AGENCY_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setAgencyFee(BigDecimal agencyFee) {
        this.agencyFee = agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REVENUE_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REVENUE_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getRevenueFee() {
        return revenueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REVENUE_FEE
     *
     * @param revenueFee the value for XUYU_CONTENT_CARD_MGR.REVENUE_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRevenueFee(BigDecimal revenueFee) {
        this.revenueFee = revenueFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.LASTMONTH_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.LASTMONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getLastmonthFee() {
        return lastmonthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.LASTMONTH_FEE
     *
     * @param lastmonthFee the value for XUYU_CONTENT_CARD_MGR.LASTMONTH_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setLastmonthFee(BigDecimal lastmonthFee) {
        this.lastmonthFee = lastmonthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REMAIN_FEE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REMAIN_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getRemainFee() {
        return remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REMAIN_FEE
     *
     * @param remainFee the value for XUYU_CONTENT_CARD_MGR.REMAIN_FEE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRemainFee(BigDecimal remainFee) {
        this.remainFee = remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.REAL_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.REAL_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getRealProfit() {
        return realProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.REAL_PROFIT
     *
     * @param realProfit the value for XUYU_CONTENT_CARD_MGR.REAL_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setRealProfit(BigDecimal realProfit) {
        this.realProfit = realProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.AGENCY_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getAgencyProfit() {
        return agencyProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.AGENCY_PROFIT
     *
     * @param agencyProfit the value for XUYU_CONTENT_CARD_MGR.AGENCY_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setAgencyProfit(BigDecimal agencyProfit) {
        this.agencyProfit = agencyProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MARK
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MARK
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MARK
     *
     * @param mark the value for XUYU_CONTENT_CARD_MGR.MARK
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.PARENT_AGENTCY
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.PARENT_AGENTCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getParentAgentcy() {
        return parentAgentcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.PARENT_AGENTCY
     *
     * @param parentAgentcy the value for XUYU_CONTENT_CARD_MGR.PARENT_AGENTCY
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setParentAgentcy(String parentAgentcy) {
        this.parentAgentcy = parentAgentcy == null ? null : parentAgentcy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MARK_FIRST
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MARK_FIRST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getMarkFirst() {
        return markFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MARK_FIRST
     *
     * @param markFirst the value for XUYU_CONTENT_CARD_MGR.MARK_FIRST
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setMarkFirst(String markFirst) {
        this.markFirst = markFirst == null ? null : markFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MARK_PROFIT
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MARK_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public BigDecimal getMarkProfit() {
        return markProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MARK_PROFIT
     *
     * @param markProfit the value for XUYU_CONTENT_CARD_MGR.MARK_PROFIT
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setMarkProfit(BigDecimal markProfit) {
        this.markProfit = markProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.CREATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.CREATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.CREATE_DATE
     *
     * @param createDate the value for XUYU_CONTENT_CARD_MGR.CREATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.CREATE_USER
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.CREATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.CREATE_USER
     *
     * @param createUser the value for XUYU_CONTENT_CARD_MGR.CREATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.UPDATE_DATE
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.UPDATE_DATE
     *
     * @param updateDate the value for XUYU_CONTENT_CARD_MGR.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.UPDATE_USER
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.UPDATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.UPDATE_USER
     *
     * @param updateUser the value for XUYU_CONTENT_CARD_MGR.UPDATE_USER
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.IMPORT_BATCHNO
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.IMPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getImportBatchno() {
        return importBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.IMPORT_BATCHNO
     *
     * @param importBatchno the value for XUYU_CONTENT_CARD_MGR.IMPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setImportBatchno(String importBatchno) {
        this.importBatchno = importBatchno == null ? null : importBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.EXPORT_BATCHNO
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.EXPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getExportBatchno() {
        return exportBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.EXPORT_BATCHNO
     *
     * @param exportBatchno the value for XUYU_CONTENT_CARD_MGR.EXPORT_BATCHNO
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setExportBatchno(String exportBatchno) {
        this.exportBatchno = exportBatchno == null ? null : exportBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_CONTENT_CARD_MGR.MANAGER_FLAG
     *
     * @return the value of XUYU_CONTENT_CARD_MGR.MANAGER_FLAG
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public String getManagerFlag() {
        return managerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_CONTENT_CARD_MGR.MANAGER_FLAG
     *
     * @param managerFlag the value for XUYU_CONTENT_CARD_MGR.MANAGER_FLAG
     *
     * @mbggenerated Sun Mar 31 19:04:26 CST 2019
     */
    public void setManagerFlag(String managerFlag) {
        this.managerFlag = managerFlag == null ? null : managerFlag.trim();
    }

	public String getAgencyName() {
		return agencyName;
	}

	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	public String getTestType() {
		return testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	public String getCardType() {
		return cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getStandard() {
		return standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public BigDecimal getRealTotalGprs() {
		return realTotalGprs;
	}

	public void setRealTotalGprs(BigDecimal realTotalGprs) {
		this.realTotalGprs = realTotalGprs;
	}

	public BigDecimal getRealRemainGps() {
		return realRemainGps;
	}

	public void setRealRemainGps(BigDecimal realRemainGps) {
		this.realRemainGps = realRemainGps;
	}

	public String getRealTestType() {
		return realTestType;
	}

	public void setRealTestType(String realTestType) {
		this.realTestType = realTestType;
	}

	public String getRealWaitType() {
		return realWaitType;
	}

	public void setRealWaitType(String realWaitType) {
		this.realWaitType = realWaitType;
	}

	public Date getRealWaitDate() {
		return realWaitDate;
	}

	public void setRealWaitDate(Date realWaitDate) {
		this.realWaitDate = realWaitDate;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

    
    
}
