package com.xuyurepos.entity.payment;

public class XuyuPayaddress {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_PAYADDRESS.ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_PAYADDRESS.AGENCY_ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    private String agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_PAYADDRESS.UUID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_PAYADDRESS.ADDRESS
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_PAYADDRESS.TYPE
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    private String type;
    
    private String orgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_PAYADDRESS.ID
     *
     * @return the value of XUYU_PAYADDRESS.ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_PAYADDRESS.ID
     *
     * @param id the value for XUYU_PAYADDRESS.ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_PAYADDRESS.AGENCY_ID
     *
     * @return the value of XUYU_PAYADDRESS.AGENCY_ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_PAYADDRESS.AGENCY_ID
     *
     * @param agencyId the value for XUYU_PAYADDRESS.AGENCY_ID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_PAYADDRESS.UUID
     *
     * @return the value of XUYU_PAYADDRESS.UUID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_PAYADDRESS.UUID
     *
     * @param uuid the value for XUYU_PAYADDRESS.UUID
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_PAYADDRESS.ADDRESS
     *
     * @return the value of XUYU_PAYADDRESS.ADDRESS
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_PAYADDRESS.ADDRESS
     *
     * @param address the value for XUYU_PAYADDRESS.ADDRESS
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_PAYADDRESS.TYPE
     *
     * @return the value of XUYU_PAYADDRESS.TYPE
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_PAYADDRESS.TYPE
     *
     * @param type the value for XUYU_PAYADDRESS.TYPE
     *
     * @mbggenerated Wed May 08 10:26:05 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
    
    


}
