package com.xuyurepos.entity.system;

import java.io.Serializable;
import java.util.Date;
/**
 * 系统关联附件表
 * @author yangfei
 *
 */
@SuppressWarnings("serial")
public class SystemAnnexe implements Serializable{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.ANNEXE_ID
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String annexeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.ANNEXE_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String annexeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.CREATE_TIME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.ANNEXE_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String annexeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.ANNEXE_SIZE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private Double annexeSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.RELATION_INFO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String relationInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.RELATION_MOD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String relationMod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.UPLOAD_USER
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String uploadUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.UPLOAD_USER_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String uploadUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.UPLOAD_PATH
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String uploadPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.UPLOAD_BATCHNO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String uploadBatchno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.COMBO_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String comboType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.WAIT_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String waitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.TEST_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String testType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.CARD_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ANNEXE.STANDARD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    private String standard;
    
    private String unitCost;
    
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.ANNEXE_ID
     *
     * @return the value of SYSTEM_ANNEXE.ANNEXE_ID
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getAnnexeId() {
        return annexeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.ANNEXE_ID
     *
     * @param annexeId the value for SYSTEM_ANNEXE.ANNEXE_ID
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setAnnexeId(String annexeId) {
        this.annexeId = annexeId == null ? null : annexeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.ANNEXE_NAME
     *
     * @return the value of SYSTEM_ANNEXE.ANNEXE_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getAnnexeName() {
        return annexeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.ANNEXE_NAME
     *
     * @param annexeName the value for SYSTEM_ANNEXE.ANNEXE_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setAnnexeName(String annexeName) {
        this.annexeName = annexeName == null ? null : annexeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.CREATE_TIME
     *
     * @return the value of SYSTEM_ANNEXE.CREATE_TIME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.CREATE_TIME
     *
     * @param createTime the value for SYSTEM_ANNEXE.CREATE_TIME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.ANNEXE_TYPE
     *
     * @return the value of SYSTEM_ANNEXE.ANNEXE_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getAnnexeType() {
        return annexeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.ANNEXE_TYPE
     *
     * @param annexeType the value for SYSTEM_ANNEXE.ANNEXE_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setAnnexeType(String annexeType) {
        this.annexeType = annexeType == null ? null : annexeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.ANNEXE_SIZE
     *
     * @return the value of SYSTEM_ANNEXE.ANNEXE_SIZE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public Double getAnnexeSize() {
        return annexeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.ANNEXE_SIZE
     *
     * @param annexeSize the value for SYSTEM_ANNEXE.ANNEXE_SIZE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setAnnexeSize(Double annexeSize) {
        this.annexeSize = annexeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.RELATION_INFO
     *
     * @return the value of SYSTEM_ANNEXE.RELATION_INFO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getRelationInfo() {
        return relationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.RELATION_INFO
     *
     * @param relationInfo the value for SYSTEM_ANNEXE.RELATION_INFO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setRelationInfo(String relationInfo) {
        this.relationInfo = relationInfo == null ? null : relationInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.RELATION_MOD
     *
     * @return the value of SYSTEM_ANNEXE.RELATION_MOD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getRelationMod() {
        return relationMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.RELATION_MOD
     *
     * @param relationMod the value for SYSTEM_ANNEXE.RELATION_MOD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setRelationMod(String relationMod) {
        this.relationMod = relationMod == null ? null : relationMod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.UPLOAD_USER
     *
     * @return the value of SYSTEM_ANNEXE.UPLOAD_USER
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getUploadUser() {
        return uploadUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.UPLOAD_USER
     *
     * @param uploadUser the value for SYSTEM_ANNEXE.UPLOAD_USER
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setUploadUser(String uploadUser) {
        this.uploadUser = uploadUser == null ? null : uploadUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.UPLOAD_USER_NAME
     *
     * @return the value of SYSTEM_ANNEXE.UPLOAD_USER_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getUploadUserName() {
        return uploadUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.UPLOAD_USER_NAME
     *
     * @param uploadUserName the value for SYSTEM_ANNEXE.UPLOAD_USER_NAME
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setUploadUserName(String uploadUserName) {
        this.uploadUserName = uploadUserName == null ? null : uploadUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.UPLOAD_PATH
     *
     * @return the value of SYSTEM_ANNEXE.UPLOAD_PATH
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getUploadPath() {
        return uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.UPLOAD_PATH
     *
     * @param uploadPath the value for SYSTEM_ANNEXE.UPLOAD_PATH
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setUploadPath(String uploadPath) {
        this.uploadPath = uploadPath == null ? null : uploadPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.UPLOAD_BATCHNO
     *
     * @return the value of SYSTEM_ANNEXE.UPLOAD_BATCHNO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getUploadBatchno() {
        return uploadBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.UPLOAD_BATCHNO
     *
     * @param uploadBatchno the value for SYSTEM_ANNEXE.UPLOAD_BATCHNO
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setUploadBatchno(String uploadBatchno) {
        this.uploadBatchno = uploadBatchno == null ? null : uploadBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.COMBO_TYPE
     *
     * @return the value of SYSTEM_ANNEXE.COMBO_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getComboType() {
        return comboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.COMBO_TYPE
     *
     * @param comboType the value for SYSTEM_ANNEXE.COMBO_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setComboType(String comboType) {
        this.comboType = comboType == null ? null : comboType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.WAIT_TYPE
     *
     * @return the value of SYSTEM_ANNEXE.WAIT_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getWaitType() {
        return waitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.WAIT_TYPE
     *
     * @param waitType the value for SYSTEM_ANNEXE.WAIT_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setWaitType(String waitType) {
        this.waitType = waitType == null ? null : waitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.TEST_TYPE
     *
     * @return the value of SYSTEM_ANNEXE.TEST_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getTestType() {
        return testType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.TEST_TYPE
     *
     * @param testType the value for SYSTEM_ANNEXE.TEST_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setTestType(String testType) {
        this.testType = testType == null ? null : testType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.CARD_TYPE
     *
     * @return the value of SYSTEM_ANNEXE.CARD_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.CARD_TYPE
     *
     * @param cardType the value for SYSTEM_ANNEXE.CARD_TYPE
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ANNEXE.STANDARD
     *
     * @return the value of SYSTEM_ANNEXE.STANDARD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ANNEXE.STANDARD
     *
     * @param standard the value for SYSTEM_ANNEXE.STANDARD
     *
     * @mbggenerated Sun Apr 14 21:50:45 CST 2019
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

	public String getUnitCost() {
        return unitCost;
	}

	public void setUnitCost(String unitCost) {
		//this.unitCost = unitCost == null ? "0" : (unitCost.equals("")  ? "0": unitCost.trim());
        this.unitCost = unitCost == null ? null : unitCost.trim();
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	
    

}
