package com.xuyurepos.entity.system;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class XuyuDown implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.ORG_ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.CREATE_DATE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.CREATE_USER
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.FILENAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.FILEPATH
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.ANNEXE_NAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String annexeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XUYU_DOWN.DOWN_TYPE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    private String downType;
    
    
    private String statu;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.ID
     *
     * @return the value of XUYU_DOWN.ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.ID
     *
     * @param id the value for XUYU_DOWN.ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.ORG_ID
     *
     * @return the value of XUYU_DOWN.ORG_ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.ORG_ID
     *
     * @param orgId the value for XUYU_DOWN.ORG_ID
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.CREATE_DATE
     *
     * @return the value of XUYU_DOWN.CREATE_DATE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.CREATE_DATE
     *
     * @param createDate the value for XUYU_DOWN.CREATE_DATE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.CREATE_USER
     *
     * @return the value of XUYU_DOWN.CREATE_USER
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.CREATE_USER
     *
     * @param createUser the value for XUYU_DOWN.CREATE_USER
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.FILENAME
     *
     * @return the value of XUYU_DOWN.FILENAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.FILENAME
     *
     * @param filename the value for XUYU_DOWN.FILENAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.FILEPATH
     *
     * @return the value of XUYU_DOWN.FILEPATH
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.FILEPATH
     *
     * @param filepath the value for XUYU_DOWN.FILEPATH
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.ANNEXE_NAME
     *
     * @return the value of XUYU_DOWN.ANNEXE_NAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getAnnexeName() {
        return annexeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.ANNEXE_NAME
     *
     * @param annexeName the value for XUYU_DOWN.ANNEXE_NAME
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setAnnexeName(String annexeName) {
        this.annexeName = annexeName == null ? null : annexeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XUYU_DOWN.DOWN_TYPE
     *
     * @return the value of XUYU_DOWN.DOWN_TYPE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public String getDownType() {
        return downType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XUYU_DOWN.DOWN_TYPE
     *
     * @param downType the value for XUYU_DOWN.DOWN_TYPE
     *
     * @mbggenerated Tue Jun 18 13:28:44 CST 2019
     */
    public void setDownType(String downType) {
        this.downType = downType == null ? null : downType.trim();
    }

	public String getStatu() {
		return statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	@Override
	public String toString() {
		return "XuyuDown [id=" + id + ", orgId=" + orgId + ", createDate=" + createDate + ", createUser=" + createUser
				+ ", filename=" + filename + ", filepath=" + filepath + ", annexeName=" + annexeName + ", downType="
				+ downType + ", statu=" + statu + "]";
	}
    
    
}